### ISSUE TITLE
JUnit Launching broken on installation of Xpect

### ISSUE THREAD

**Issue by JoostvanPinxten** [meysholdt/Xpect#166]
Coming from a clean Eclipse 4.4 SR2, I install Xtext, create the domain model example, and I can still run JUnit tests by selecting 'Run As' -> 'JUnit Test'. However, after I install Xpect, I cannot run any kind of JUnit test, as I get a NullPointerException:
```
!ENTRY org.eclipse.core.jobs 4 2 2015-03-29 23:17:02.242
!MESSAGE An internal error occurred during: "Launching Something".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.localURL(JUnitLaunchConfigurationDelegate.java:429)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.entryString(JUnitLaunchConfigurationDelegate.java:418)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.addEntry(JUnitLaunchConfigurationDelegate.java:405)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.localizeClasspath(JUnitLaunchConfigurationDelegate.java:396)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getClasspath(JUnitLaunchConfigurationDelegate.java:373)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:147)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

I am running Windows 7, 64-bit and the 64-bit version of Luna SR2 (Same problem with 4.4.0 and 4.4.1 though)... Is it possible the current 'nightly'  build is broken, even though the last commit was 2 months ago?

**Comment by JoostvanPinxten** [comment]
It works properly when I import the projects from GitHub and then create a runtime Eclipse instance... Is the update site properly up to date?

**Comment by meysholdt** [comment]
This already was reported in #164, please see my comments there for an explanation.

**Comment by JoostvanPinxten** [comment]
Thanks for the reply!
