### ISSUE TITLE
Port to Xtext 2.8.x

### ISSUE THREAD

**Issue by cdietrich** [meysholdt/Xpect#167]

**Comment by Staalk** [comment]
My first try of xpect was with the nice direct to the point tutorial on http://www.xpect-tests.org/. I have xtext 2.8.x installed and sadly the tutorial didnt work. I downgraded to xtext 2.7.3 and now it seems to work fine.

Can we expect an update to support Xtext version 2.8.x. I think every project using Xpect will eventually upgrade

**Comment by cdietrich** [comment]
java.lang.NoSuchMethodError: org.eclipse.xtext.common.types.access.ClasspathTypeProviderFactory.<init>(Ljava/lang/ClassLoader;)V
	at org.xpect.ui.util.XpectFileAccess.cloneResourceSet(XpectFileAccess.java:54)
	at org.xpect.ui.util.XpectFileAccess.getXpectResource(XpectFileAccess.java:89)
	at org.xpect.ui.util.XpectFileAccess.getXpectFile(XpectFileAccess.java:74)
	at org.xpect.xtext.lib.tests.ValidationTestModuleSetup$TestingResourceValidator.validateAndMapByOffset(ValidationTestModuleSetup.java:101)
	at org.xpect.xtext.lib.tests.ValidationTestModuleSetup$IssuesByOffsetSetup.collectIssuesByLine(ValidationTestModuleSetup.java:68)
	at org.xpect.xtext.lib.tests.ValidationTestModuleSetup$IssuesByOffsetSetup.collectIssues(ValidationTestModuleSetup.java:60)
	at org.xpect.xtext.lib.setup.XtextValidatingSetup.getIssues(XtextValidatingSetup.java:91)
	at org.xpect.xtext.lib.setup.XtextValidatingSetup.validate(XtextValidatingSetup.java:116)
	at org.xpect.runner.XpectFileRunner.run(XpectFileRunner.java:231)
	at org.xpect.runner.XpectRunner.runChild(XpectRunner.java:184)
	at org.xpect.runner.XpectRunner.runChild(XpectRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.xpect.runner.XpectRunner.run(XpectRunner.java:170)
	at org.eclipse.jdt.junit4.runtime.patch.JUnit4TestReference.run(JUnit4TestReference.java:42)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by cdietrich** [comment]
it seem to work if i build the current master with 2.7.x and use the exported feature in 2.8.x. Building with 2.8.x does not work since xtext confuses the jvmtypes metamodel

**Comment by cdietrich** [comment]
created https://github.com/meysholdt/Xpect/pull/169

**Comment by ivarru** [comment]
Will the update site (http://www.xpect-tests.org/updatesite/nightly/) be updated when this is fixed?

**Comment by meysholdt** [comment]
hey, yes, I've updated the update site  http://www.xpect-tests.org/updatesite/nightly/ with a version of Xpect that's fully compatible with Eclipse Mars and Xtext 2.8.3 (as release with Eclipse Mars) and Xtext 2.8.4 (as released last week).

There was an interim update site called 'nightly-mars', which I have removed again. Please use the update site mentioned above.
