### ISSUE TITLE
NullpointerException during Unit Test

### ISSUE THREAD

**Issue by xSmorpheusSx** [meysholdt/Xpect#189]
java.lang.NullPointerException
	at org.xpect.util.XpectJavaModelManager.getTypeReferences(XpectJavaModelManager.java:81)
	at org.xpect.util.XpectJavaModelManager.createJavaModel(XpectJavaModelManager.java:28)
	at org.xpect.runner.XpectRunner.<init>(XpectRunner.java:76)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

My Test Class:

package test;

import org.junit.runner.RunWith;
import org.xpect.runner.XpectRunner;
import org.xpect.runner.XpectTestFiles;
import org.xpect.xtext.lib.tests.XtextTests;

@RunWith(XpectRunner.class)
@XpectTestFiles(fileExtensions = "xt")
public class TestDModel extends XtextTests {

}
 

The XT File:

/* XPECT_SETUP test.TestDModel    
    
   END_SETUP
 */ 
 
package pkg1 { 
  entity MyEntity1 {
    
    // int should be the java primitive
    // XPECT linkedName at int --> int
    id:int
    
    // String should be from java.lang 
    // XPECT linkedName at String --> java.lang.String
    name:String
  }
}

**Comment by Staalk** [comment]
i got the same error. Did you find the solution?

**Comment by cdietrich** [comment]
i think Xpect should do something like

```
((XtextResource) targetResource).getResourceServiceProvider().get(org.eclipse.xtext.resource.IGlobalServiceProvider.class)
.findService(targetObject, org.eclipse.xtext.naming.IQualifiedNameProvider.class)
.getFullyQualifiedName(targetObject)
```
